version: '2'
services:
  node-exporter:
    image: node-exporter:latest
    stdin_open: true
    tty: true
    ports:
    - 13004:9100/tcp
    
  cadvisor:
    image: cadvisor:v0.25.0
    stdin_open: true
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    tty: true
    ports:
    - 13005:8080/tcp
